### ISSUE TITLE
Tap is broken

### ISSUE THREAD

**Issue by martinlechner1** [tenpureto/tenpureto#129]
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/rtimush/homebrew-tap/Formula/brittany.rb
brittany: Calling include Language::Haskell::Cabal is disabled! There is no replacement.
Please report this issue to the rtimush/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/rtimush/homebrew-tap/Formula/brittany.rb:4

Error: Cannot tap rtimush/tap: invalid syntax in tap!

It is reproducible by running
```
brew untap rtimush/tap
brew tap rtimush/tap
```

**Comment by rtimush** [comment]
Fixed by removing an unused brittany formula, thanks for reporting

**Comment by martinlechner1** [comment]
Thanks Roman!
