### ISSUE TITLE
Variables order is not preserved

### ISSUE THREAD

**Issue by rtimush** [tenpureto/tenpureto#13]
Although variables are defined as `InsOrdHashMap Text Text`, the order is not preserved during YAML parsing. In general, YAML dictionaries are unordered, so it YAML parser doesn't have to preserve the order. However, from a user's perspective, the order matters.

**Comment by reflectiondm** [comment]
Looks like the variables are sorted alphabetically, so prefixing them with numbers for example is okay-ish workaround. but would be nice to fix it somehow.
