### ISSUE TITLE
Add badges on main readme (build/dependencies etc)

### ISSUE THREAD

**Issue by inakianduaga** [tenpureto/tenpureto#15]
Any project worth its salt has a lot of badges on top.... 

But more seriously, build status, maybe dependency versions and test coverage are quite important to indicate professionalism and quality for new users

Add badges for:

- [x] Build status (hopefully it's green)
- [ ] Code coverage
- [ ] Last version build (if possible)

for some you might be able to use shields.io

**Comment by rtimush** [comment]
Partially addressed in d1b0186f695577146c4bedb81b81f1cd5eb44bc9
