### ISSUE TITLE
Add a command to adopt an existing project

### ISSUE THREAD

**Issue by rtimush** [tenpureto/tenpureto#21]
It would be nice to have an easy way to adopt existing projects that were not created from a template, some mix of `tenpureto create` and `tenpureto update`. This will allow the project to receive future updates from the template.

A possible workflow is
 1. Create an empty orphan commit
```sh
git checkout --orphan template
git commit --allow-empty -m "Initial empty template commit"
```
2. Run `tenpureto update` specifying this commit as a parent:
```sh
tenpureto update --previous-commit $(git rev-parse HEAD)
```
3. Merge with the original project branch and resolve conflicts.

**Comment by simonmit** [comment]
One tiny remark: You are missing the `-m` for the commit message.

**Comment by rtimush** [comment]
@simonmit Thanks, fixed
