### ISSUE TITLE
Cannot be installed with linuxbrew

### ISSUE THREAD

**Issue by bdadam** [tenpureto/tenpureto#35]
When running `brew install tenpureto` with [Homebrew on Linux](https://docs.brew.sh/Homebrew-on-Linux) it doesn't work.
During installation I see that it downloads the macOS version of GHC
`==> Downloading https://downloads.haskell.org/~ghc/8.4.4/ghc-8.4.4-x86_64-apple-darwin.tar.xz`
and later also tries to use it.
In the console I can see:
```
xec: utils/ghc-cabal/dist-install/build/tmp/ghc-cabal: Exec format error
make[1]: *** [ghc.mk:1001: install_packages] Error 2
make: *** [Makefile:51: install] Error 2
```

**Comment by rtimush** [comment]
The problem is that https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/haskell-stack.rb depends on an OSX distribution and therefore doesn't work on linux. I will probably report upstream.

**Comment by rtimush** [comment]
Now tenpureto can be installed with linuxbrew
