### ISSUE TITLE
What does a tenpureto template actually look like?

### ISSUE THREAD

**Issue by kozross** [tenpureto/tenpureto#7]
Is there an example provided? If so, the README should direct you to it much more clearly. If not, there should be one.

**Comment by rtimush** [comment]
There is no public example yet, but I definitely need to add the docs, and also create some sample template.

**Comment by kozross** [comment]
I'm happy to help document things if you like.

**Comment by rtimush** [comment]
I guess it can be tricky to gather the knowledge scattered across the source files about what I have in mind about the template structure, so it will probably be easier if I add some docs first. However, then it will be super valuable to get feedback on what is clear and what's not from the external perspective.

**Comment by rtimush** [comment]
Finally wrote some docs, available at https://tenpureto.org
